/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as PagesSlugRouteImport } from './routes/pages.$slug'
import { Route as ApiSeoRouteImport } from './routes/api.seo'
import { Route as ApiCatalogRouteImport } from './routes/api.catalog'
import { Route as ApiObservabilitySplatRouteImport } from './routes/api.observability.$'
import { Route as ApiCommerceSplatRouteImport } from './routes/api.commerce.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSlugRoute = PagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeoRoute = ApiSeoRouteImport.update({
  id: '/api/seo',
  path: '/api/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogRoute = ApiCatalogRouteImport.update({
  id: '/api/catalog',
  path: '/api/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiObservabilitySplatRoute = ApiObservabilitySplatRouteImport.update({
  id: '/api/observability/$',
  path: '/api/observability/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommerceSplatRoute = ApiCommerceSplatRouteImport.update({
  id: '/api/commerce/$',
  path: '/api/commerce/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/brands': typeof BrandsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/products': typeof ProductsRoute
  '/wishlist': typeof WishlistRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/seo': typeof ApiSeoRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/product/$id': typeof ProductIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/commerce/$': typeof ApiCommerceSplatRoute
  '/api/observability/$': typeof ApiObservabilitySplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/brands': typeof BrandsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/products': typeof ProductsRoute
  '/wishlist': typeof WishlistRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/seo': typeof ApiSeoRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/product/$id': typeof ProductIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/commerce/$': typeof ApiCommerceSplatRoute
  '/api/observability/$': typeof ApiObservabilitySplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/brands': typeof BrandsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/products': typeof ProductsRoute
  '/wishlist': typeof WishlistRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/seo': typeof ApiSeoRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/product/$id': typeof ProductIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/commerce/$': typeof ApiCommerceSplatRoute
  '/api/observability/$': typeof ApiObservabilitySplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/brands'
    | '/cart'
    | '/checkout'
    | '/products'
    | '/wishlist'
    | '/api/catalog'
    | '/api/seo'
    | '/pages/$slug'
    | '/product/$id'
    | '/api/auth/$'
    | '/api/commerce/$'
    | '/api/observability/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/brands'
    | '/cart'
    | '/checkout'
    | '/products'
    | '/wishlist'
    | '/api/catalog'
    | '/api/seo'
    | '/pages/$slug'
    | '/product/$id'
    | '/api/auth/$'
    | '/api/commerce/$'
    | '/api/observability/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/brands'
    | '/cart'
    | '/checkout'
    | '/products'
    | '/wishlist'
    | '/api/catalog'
    | '/api/seo'
    | '/pages/$slug'
    | '/product/$id'
    | '/api/auth/$'
    | '/api/commerce/$'
    | '/api/observability/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  BrandsRoute: typeof BrandsRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ProductsRoute: typeof ProductsRoute
  WishlistRoute: typeof WishlistRoute
  ApiCatalogRoute: typeof ApiCatalogRoute
  ApiSeoRoute: typeof ApiSeoRoute
  PagesSlugRoute: typeof PagesSlugRoute
  ProductIdRoute: typeof ProductIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCommerceSplatRoute: typeof ApiCommerceSplatRoute
  ApiObservabilitySplatRoute: typeof ApiObservabilitySplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$slug': {
      id: '/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof PagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seo': {
      id: '/api/seo'
      path: '/api/seo'
      fullPath: '/api/seo'
      preLoaderRoute: typeof ApiSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog': {
      id: '/api/catalog'
      path: '/api/catalog'
      fullPath: '/api/catalog'
      preLoaderRoute: typeof ApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/observability/$': {
      id: '/api/observability/$'
      path: '/api/observability/$'
      fullPath: '/api/observability/$'
      preLoaderRoute: typeof ApiObservabilitySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/commerce/$': {
      id: '/api/commerce/$'
      path: '/api/commerce/$'
      fullPath: '/api/commerce/$'
      preLoaderRoute: typeof ApiCommerceSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  BrandsRoute: BrandsRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ProductsRoute: ProductsRoute,
  WishlistRoute: WishlistRoute,
  ApiCatalogRoute: ApiCatalogRoute,
  ApiSeoRoute: ApiSeoRoute,
  PagesSlugRoute: PagesSlugRoute,
  ProductIdRoute: ProductIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCommerceSplatRoute: ApiCommerceSplatRoute,
  ApiObservabilitySplatRoute: ApiObservabilitySplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
